# Generated by Django 4.1.3 on 2022-11-25 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('buildingID', models.AutoField(primary_key=True, serialize=False)),
                ('buildingName', models.CharField(max_length=100)),
                ('phoneNo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Food_Plan',
            fields=[
                ('type', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('days', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ssn', models.CharField(max_length=9)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone_num', models.CharField(max_length=10, null=True)),
                ('is_student', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_technician', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomNo', models.CharField(max_length=6)),
                ('buildingID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.building')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.person')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('staff_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.staff')),
                ('position', models.CharField(max_length=100, null=True)),
            ],
            bases=('app.staff',),
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('staff_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.staff')),
                ('specialization', models.CharField(max_length=100, null=True)),
            ],
            bases=('app.staff',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.person')),
                ('year', models.IntegerField()),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.food_plan')),
            ],
        ),
        migrations.CreateModel(
            name='Room_Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.room')),
                ('studentID', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.student')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('paymentID', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('amount', models.IntegerField()),
                ('studentID', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.student')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('maintenanceID', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('room', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.room')),
                ('studentID', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.student')),
            ],
        ),
        migrations.CreateModel(
            name='Fulfills_Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenanceID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.maintenance')),
                ('technicianID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.technician')),
            ],
        ),
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('complainID', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('details', models.CharField(max_length=1000)),
                ('student', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.student')),
                ('admin', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.admin')),
            ],
        ),
    ]
