# Generated by Django 4.1.3 on 2022-11-27 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_complain_status_person_password_alter_complain_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='status',
            field=models.CharField(choices=[('RESOLVED', 'RESOLVED'), ('IN PROGRESS', 'IN PROGRESS'), ('NOT RESOLVED', 'NOT RESOLVED')], default='NOT RESOLVED', max_length=20),
        ),
        migrations.AddField(
            model_name='person',
            name='first_name',
            field=models.CharField(default=100, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='last_name',
            field=models.CharField(default=100, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='complain',
            name='status',
            field=models.CharField(choices=[('RESOLVED', 'RESOLVED'), ('IN PROGRESS', 'IN PROGRESS'), ('NOT RESOLVED', 'NOT RESOLVED')], default='NOT RESOLVED', max_length=20),
        ),
    ]
