# Generated by Django 4.1.3 on 2022-11-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_person_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='password',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
