# Generated by Django 4.1.3 on 2022-11-29 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_person_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='details',
            field=models.TextField(default=101),
            preserve_default=False,
        ),
    ]
