# Generated by Django 4.1.3 on 2022-12-01 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_maintenance_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.admin'),
        ),
        migrations.AlterField(
            model_name='complain',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.student'),
        ),
    ]
