# Generated by Django 4.1.3 on 2022-12-03 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_fulfills_maintenance_id_alter_room_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='first_name',
            field=models.CharField(default='100', max_length=30),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='last_name',
            field=models.CharField(default='100', max_length=30),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(default=199, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='major',
            field=models.CharField(default=199, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='studentID',
            field=models.CharField(default=199, max_length=8),
            preserve_default=False,
        ),
    ]
