# Generated by Django 4.1.3 on 2022-12-03 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_maintenance_first_name_maintenance_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.room'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='studentID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.student'),
        ),
    ]
