# Generated by Django 4.1.3 on 2022-12-08 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_complain_first_name_complain_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('mailID', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('studentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.student')),
            ],
        ),
    ]
