# Generated by Django 4.1.3 on 2022-12-08 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='pickedUp',
            field=models.BooleanField(default=False),
        ),
    ]
